"""
Django settings for core_project project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from datetime import timedelta
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["localhost", "127.0.0.1"]

import sys
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.users',
    'apps.documents',
    'apps.interviews',
    'apps.ai_services',
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt',
    'django_redis',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core_project.urls'

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5174",
    "https://ai-studybrain.vercel.app"
]
CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = [
    "https://ai-studybrain.vercel.app"
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core_project.wsgi.application'

JAZZMIN_SETTINGS = {
    "site_title": "AI Assistant Admin",
    "site_header": "AI Learning Assistant",
    "site_brand": "AI Admin",
    "welcome_sign": "Welcome to the AI Learning Assistant Control Panel",
    "custom_css": "css/admin_custom.css",
    "copyright": "AI Assistant",

    "order_with_respect_to": [
        "ai_services",
        "documents",
        "interviews",
        "users",
        "auth",
    ],
        "icons": {

        # AI Services
        "ai_services": "fas fa-brain",
        "ai_services.apilog": "fas fa-server",
        "ai_services.generatedcontent": "fas fa-file-alt",

        # Documents
        "documents": "fas fa-file",
        "documents.document": "fas fa-file-pdf",

        # Interviews
        "interviews": "fas fa-microphone",
        "interviews.interviewsession": "fas fa-comments",
        "interviews.interviewresponse": "fas fa-reply",

        # Users
        "users": "fas fa-users",
        "users.user": "fas fa-user",
        "users.transaction": "fas fa-credit-card",

        # Auth
        "auth": "fas fa-lock",
        "auth.user": "fas fa-user-shield",
        "auth.group": "fas fa-users-cog",
    },
    "navigation_expanded": True,
    "show_sidebar": True,
    "sidebar_fixed": True,
    "search_model": ["users.User", "documents.Document"],
    "theme": "cosmo",
    "dark_mode_theme": "darkly",
        "topmenu_links": [

        {"name": "Dashboard", "url": "admin:index", "permissions": ["auth.view_user"]},

        {"app": "documents"},

        {"app": "interviews"},

        {"app": "users"},

        {"app": "ai_services"},
    ],
        "related_modal_active": True,
}
JAZZMIN_UI_TWEAKS = {
    "theme": "cosmo",
    "login_background": "img/ai_background.png",
    "dark_mode_theme": "darkly",
    "navbar_small_text": False,
    "footer_small_text": False,
    "sidebar_nav_small_text": False,
    "navbar_fixed": True,
    "sidebar_fixed": True,
    "footer_fixed": False,
}

STATIC_URL = "/static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
         'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'learning_assistant', 
        'USER': 'root',        
        'PASSWORD': '1234',    
        'HOST': 'localhost',            
        'PORT': '3306',                 
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'users.User'

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Redis Cache Configuration
redis_url = os.getenv("REDIS_URL")
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": redis_url,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# Celery
CELERY_BROKER_URL = redis_url
CELERY_RESULT_BACKEND = redis_url

CELERY_TASK_DEFAULT_QUEUE = "celery_tasks"

CELERY_TASK_ROUTES = {
    "apps.ai_services.tasks.*": {"queue": "interview_queue"}
}

# Standard Celery Config
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# JWT Authentication Settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '10/min', # Prevents OAuth endpoint spam
        'user': '100/min'
    }
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,          # Issues a new refresh token on use
    'BLACKLIST_AFTER_ROTATION': True,       # Ensure old refresh tokens are invalidated after use
}

# Razorpay Configuration
RAZORPAY_KEY_ID = os.getenv('RAZORPAY_KEY_ID')
RAZORPAY_KEY_SECRET = os.getenv('RAZORPAY_KEY_SECRET')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
HUGGINGFACE_API_KEY = os.getenv("HUGGINGFACE_API_KEY")

RAZORPAY_WEBHOOK_SECRET = os.getenv('RAZORPAY_WEBHOOK_SECRET')

GOOGLE_CLIENT_ID = os.getenv('GOOGLE_CLIENT_ID')
GOOGLE_CLIENT_SECRET = os.getenv('GOOGLE_CLIENT_SECRET')

GITHUB_CLIENT_ID = os.getenv('GITHUB_CLIENT_ID')
GITHUB_CLIENT_SECRET = os.getenv('GITHUB_CLIENT_SECRET')

YOUTUBE_API_KEY = os.getenv('YOUTUBE_API_KEY')

import os
import cloudinary
import cloudinary.uploader
import cloudinary.api

# Cloudinary Configuration
cloudinary.config( 
  cloud_name = os.getenv('CLOUDINARY_CLOUD_NAME'), 
  api_key = os.getenv('CLOUDINARY_API_KEY'), 
  api_secret = os.getenv('CLOUDINARY_API_SECRET'),
  secure = True
)