version: '3.8'

services:
  # 1. MySQL Database
  db:
    image: mysql:8.0
    container_name: mysql_database
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql_init:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    env_file:
      - .env
      - .env.docker

  # 2. Django Web
  web:
    build: .
    image: myapp:latest
    container_name: django_api_service
    command: gunicorn core_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - app_data:/app/persistent_data
    ports:
      - "8000:8000"
    env_file:
      - .env
      - .env.docker
    restart: always
    depends_on:
      - db

  # 3. Celery Worker
  worker:
    image: myapp:latest
    container_name: celery_worker_service
    command: celery -A core_project worker --loglevel=info
    volumes:
      - .:/app
      - app_data:/app/persistent_data
    env_file:
      - .env
      - .env.docker
    restart: always
    depends_on:
      - web
      - db

volumes:
  app_data:
  mysql_data: