# Generated by Django 5.2.11 on 2026-02-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='text_chunks',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
