# Generated by Django 5.2.11 on 2026-03-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_content_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='youtube_video',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
