# Generated by Django 5.2.11 on 2026-02-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_avatar_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='payment_id',
            new_name='razorpay_payment_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='plan_type',
            field=models.CharField(default='LEGACY', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='razorpay_order_id',
            field=models.CharField(default='LEGACY', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
