# Generated by Django 5.2.11 on 2026-02-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50)),
                ('endpoint_used', models.CharField(max_length=100)),
                ('tokens_used', models.IntegerField(default=0)),
                ('latency_seconds', models.FloatField(default=0.0)),
                ('successful', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('SUMMARY', 'Summarization'), ('QUIZ', 'Quiz Generation'), ('INTERVIEW_Q', 'Interview Question Generation')], max_length=20, unique=True)),
                ('system_prompt', models.TextField(help_text='The instructions given to Gemini.')),
                ('model_version', models.CharField(default='gemini-1.5-flash', max_length=50)),
                ('temperature', models.FloatField(default=0.7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
