# Generated by Django 5.2.11 on 2026-02-24 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0002_initial'),
        ('documents', '0003_document_text_chunks'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('summary', 'Summary'), ('notes', 'Notes'), ('flashcards', 'Flashcards'), ('interview', 'Interview Context')], max_length=20)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_content', to='documents.document')),
            ],
            options={
                'unique_together': {('document', 'content_type')},
            },
        ),
    ]
