# Generated by Django 5.2.11 on 2026-02-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0003_generatedcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompttemplate',
            name='model_version',
            field=models.CharField(default='gemini-2.5-flash', max_length=50),
        ),
    ]
