# Generated by Django 5.2.11 on 2026-03-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0004_alter_prompttemplate_model_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedcontent',
            name='content_type',
            field=models.CharField(choices=[('summary', 'Summary'), ('notes', 'Notes'), ('flashcards', 'Flashcards'), ('quiz', 'Quiz'), ('interview', 'Interview Context')], max_length=20),
        ),
    ]
