# Generated by Django 5.2.11 on 2026-03-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0006_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedcontent',
            name='content_type',
            field=models.CharField(choices=[('summary', 'Summary'), ('notes', 'Notes'), ('flashcards', 'Flashcards'), ('quiz', 'Quiz'), ('interview', 'Interview Context'), ('search_query', 'Search Query')], max_length=20),
        ),
    ]
